remote_theme: mmistakes/minimal-mistakes
title: Rick's portfolio
plugins:
  - jekyll-include-cache

include: ["_pages"]

author:
  name: "Rick Theeuwes"
  bio: "A hacker with a passion for development."
  links:
    - label: "Email"
      icon: "fas fa-fw -fa-envelope-square"
      url: "mailto:r.theeuwes@student.fontys.nl"
    - label: "Github"
      icon: "fab fa-fw fa-github-square"
      url: "https://github.com/riqky"

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
